CREATE TABLE "productos" (
  "producto_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "descripcion" varchar(255),
  "precio" numeric(10,2) NOT NULL,          -- Precio original (el que se tachará)
  "precio_oferta" numeric(10,2),            -- Precio con descuento
  "en_oferta" boolean DEFAULT false,        -- ¿Está en promoción?
  "activo" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "categoria_id" integer NOT NULL
);

CREATE TABLE "categorias" (
  "categoria_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "parent_id" integer
);

CREATE TABLE "colores" (
  "color_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(30) NOT NULL
);

CREATE TABLE "sizes" (
  "size_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "valor" varchar(20) NOT NULL,
  "type_id" integer NOT NULL
);

CREATE TABLE "size_types" (
  "type_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL
);

CREATE TABLE "variantes_producto" (
  "variante_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "stock" integer NOT NULL DEFAULT 0,
  "producto_id" integer NOT NULL,
  "color_id" integer NOT NULL,
  "size_id" integer NOT NULL
);

CREATE TABLE "imagenes_productos" (
  "img_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" text NOT NULL,
  "principal" boolean DEFAULT false,
  "producto_id" integer NOT NULL
);

CREATE TABLE "clientes" (
  "cliente_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "telefono" varchar(20),
  "email" varchar(100) UNIQUE NOT NULL,
  "activo" boolean DEFAULT TRUE,
  "updated_at" timestamp DEFAULT NOW()
);

CREATE TABLE "ventas" (
  "venta_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "total" numeric(12,2) NOT NULL,
  "metodo_pago" varchar(50) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "cliente_id" integer NOT NULL,
  "estado_id" integer NOT NULL
);

CREATE TABLE "estados_venta" (
  "estado_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50) NOT NULL
);

CREATE TABLE "detalle_ventas" (
  "detalle_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cantidad" integer NOT NULL,
  "precio_unitario" numeric(12,2) NOT NULL,
  "venta_id" integer NOT NULL,
  "variante_id" integer NOT NULL
);

CREATE TABLE "productos_home" (
  "home_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orden" integer DEFAULT 0,
  "activo" boolean DEFAULT true,
  "producto_id" integer NOT NULL
);

CREATE TABLE "carousel_home" (
  "carousel_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "img_desktop_url" text NOT NULL,
  "img_mobile_url" text NOT NULL,
  "orden" integer DEFAULT 0,
  "activo" boolean DEFAULT true,
  "producto_id" integer,
  "categoria_id" integer
);

CREATE TABLE "usuarios" (
  "usuario_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "contrasenia" varchar(255) NOT NULL,
  "rol_id" integer NOT NULL
);

CREATE TABLE "roles" (
  "rol_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50) NOT NULL
);

ALTER TABLE "productos" ADD FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("categoria_id");

ALTER TABLE "categorias" ADD FOREIGN KEY ("parent_id") REFERENCES "categorias" ("categoria_id");

ALTER TABLE "sizes" ADD FOREIGN KEY ("type_id") REFERENCES "size_types" ("type_id");

ALTER TABLE "variantes_producto" ADD FOREIGN KEY ("producto_id") REFERENCES "productos" ("producto_id");

ALTER TABLE "variantes_producto" ADD FOREIGN KEY ("color_id") REFERENCES "colores" ("color_id");

ALTER TABLE "variantes_producto" ADD FOREIGN KEY ("size_id") REFERENCES "sizes" ("size_id");

ALTER TABLE "imagenes_productos" ADD FOREIGN KEY ("producto_id") REFERENCES "productos" ("producto_id");

ALTER TABLE "ventas" ADD FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("cliente_id");

ALTER TABLE "ventas" ADD FOREIGN KEY ("estado_id") REFERENCES "estados_venta" ("estado_id");

ALTER TABLE "detalle_ventas" ADD FOREIGN KEY ("venta_id") REFERENCES "ventas" ("venta_id");

ALTER TABLE "detalle_ventas" ADD FOREIGN KEY ("variante_id") REFERENCES "variantes_producto" ("variante_id");

ALTER TABLE "productos_home" ADD FOREIGN KEY ("producto_id") REFERENCES "productos" ("producto_id");

ALTER TABLE "carousel_home" ADD FOREIGN KEY ("producto_id") REFERENCES "productos" ("producto_id");

ALTER TABLE "carousel_home" ADD FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("categoria_id");

ALTER TABLE "usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("rol_id");

-- Categorías padre
INSERT INTO categorias (nombre, parent_id) VALUES
('Textiles', NULL),
('Cestería', NULL),
('Para la Mesa', NULL),
('Para la Cocina', NULL),
('Kids', NULL);

-- Subcategorías
INSERT INTO categorias (nombre, parent_id)
VALUES
('Lonitas', (SELECT categoria_id FROM categorias WHERE nombre = 'Textiles')),
('Fundas', (SELECT categoria_id FROM categorias WHERE nombre = 'Textiles')),
('Mantas', (SELECT categoria_id FROM categorias WHERE nombre = 'Textiles')),
('Almohadones', (SELECT categoria_id FROM categorias WHERE nombre = 'Kids')),
('Cestos', (SELECT categoria_id FROM categorias WHERE nombre = 'Kids')),
('Contenedores', (SELECT categoria_id FROM categorias WHERE nombre = 'Kids')),
('Alfombras', (SELECT categoria_id FROM categorias WHERE nombre = 'Kids'));
